package com.roofingcrm.domain.enums;

public enum ActivityEventType {
    NOTE,
    LEAD_STATUS_CHANGED,
    JOB_STATUS_CHANGED,
    TASK_CREATED,
    TASK_STATUS_CHANGED,
    LEAD_CONVERTED_TO_JOB,
    ATTACHMENT_ADDED,
    JOB_SCHEDULE_CHANGED,
    ESTIMATE_SHARED,
    ESTIMATE_EMAIL_SENT,
    ESTIMATE_ACCEPTED,
    ESTIMATE_REJECTED,
    INVOICE_CREATED,
    INVOICE_SHARED,
    INVOICE_EMAIL_SENT,
    INVOICE_STATUS_CHANGED,
    COST_ENTRY_CREATED,
    COST_ENTRY_UPDATED,
    COST_ENTRY_DELETED,
    RECEIPT_UPLOADED,
    RECEIPT_EXTRACTION_COMPLETED,
    RECEIPT_EXTRACTION_FAILED,
    RECEIPT_LINKED_TO_COST,
    RECEIPT_UNLINKED_FROM_COST,
    RECEIPT_DELETED
}
